# The URL the site will be built for
base_url = "https://blog.navneetaman.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "tabi"
title = "Navneet's Blog"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]

theme = "auto"
socials = [
  # Configure socials here
]
menu = [
  # Configure menu bar here
]
